Repository lirantal/lockfile-lint, pull requests merged in 2019-11, with the labels that each got.

#20 feat: provide the actual bad string in ValidateScheme
  packages/lockfile-lint-api/__tests__/validators.host.test.js
  packages/lockfile-lint-api/__tests__/validators.https.test.js
  packages/lockfile-lint-api/__tests__/validators.scheme.test.js
  packages/lockfile-lint-api/src/validators/ValidateHost.js
  packages/lockfile-lint-api/src/validators/ValidateHttps.js
  packages/lockfile-lint-api/src/validators/ValidateScheme.js
  packages/lockfile-lint/__tests__/cli.test.js
  packages/lockfile-lint/bin/lockfile-lint.js
Labels: bug, hacktoberfest

#27 feat(emptyhostname): allow empty hostnames in api
  packages/lockfile-lint-api/__tests__/validators.host.test.js
  packages/lockfile-lint-api/src/validators/ValidateHost.js
Labels: enhancement

#28 test(scheme): coverage for conditional validation check
  packages/lockfile-lint-api/__tests__/validators.scheme.test.js
Labels: enhancement

#29 Fix typo in `lockfile-link-api` README
  packages/lockfile-lint-api/README.md
Labels: bug
