Repository lirantal/lockfile-lint, pull requests merged in 2020-02, with the labels that each got.

#55 chore(build): fix deploy stage
  .travis.yml
Labels: bug

#56 docs(readme): add security disclaimer
  README.md
Labels: documentation

#57 docs(readme): add list of supported lockfiles
  packages/lockfile-lint/README.md
Labels: documentation

#53 fix(api): lint all dependencies in package-lock
  packages/lockfile-lint-api/__tests__/parseNpmLockfile.test.js
  packages/lockfile-lint-api/__tests__/validators.host.test.js
  packages/lockfile-lint-api/__tests__/validators.https.test.js
  packages/lockfile-lint-api/__tests__/validators.scheme.test.js
  packages/lockfile-lint-api/package.json
  packages/lockfile-lint-api/src/ParseLockfile.js
  packages/lockfile-lint-api/src/validators/ValidateHost.js
  packages/lockfile-lint-api/src/validators/ValidateHttps.js
  packages/lockfile-lint-api/src/validators/ValidateScheme.js
  yarn.lock
Labels: bug

#59 fix(validators): only validating when URL is present
  packages/lockfile-lint-api/src/validators/ValidateHttps.js
  packages/lockfile-lint-api/src/validators/ValidateScheme.js
Labels: bug

#61 fix(validators): host validator enforced with URLs only
  packages/lockfile-lint-api/src/validators/ValidateHost.js
Labels: bug

#64 fix(cli): conflicting arguments will error
  packages/lockfile-lint/__tests__/cli.test.js
  packages/lockfile-lint/src/cli.js
Labels: bug

#66 fix(build): double quote globs in npm scripts
  packages/lockfile-lint-api/package.json
  packages/lockfile-lint/package.json
Labels: enhancement

#71 Fix tests on Windows
  packages/lockfile-lint/__tests__/cli.test.js
Labels: bug

#72 feat(cli): error on conflicting options
  packages/lockfile-lint/__tests__/cli.test.js
  packages/lockfile-lint/src/cli.js
Labels: enhancement
